### ISSUE TITLE
Do not understand how to execute deployer

### ISSUE THREAD

**Issue by DenisTis** [mauriciolauffer/ui5-deployer-app-test#6]
Hi Mauricio, 
thanks a lot for providing this functionality for ui5 tools!

I have latest ui5-cli (2.6.5) and it does not work for me. 
I created ui5.yaml file as indicated, but when I call it via: 
"ui5 deploy" it complains, that deploy command is unknown.
"ui5-deployer deploy" is not recognized as command (though I installed ui5-deployer as local dev and as global dependencies).

Could you please indicate what did I do wrong?

**Comment by mauriciolauffer** [comment]
This is just a sample app to test [ui5-deployer](https://www.npmjs.com/package/ui5-deployer) module, which is not part of ui5-cli and needs to be installed.
